apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-acg
  region: us-east-2
  version: "1.29"
vpc:
  cidr: 10.0.0.0/16
managedNodeGroups:
  - name: eks-node-group
    instanceType: t2.medium
    desiredCapacity: 3
    privateNetworking: true
