apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekstar-bookstore-internal-ingress
  namespace: development
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:590183757374:certificate/481e194e-0916-4c9e-a3f7-f5f7906e1c4e
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=360
    external-dns.alpha.kubernetes.io/hostname: >-
      renting-api.dev.theprimetech1.com, resource-api.dev.theprimetech1.com,
      inventory-api.dev.theprimetech1.com, clients-api.dev.theprimetech1.com,
      bookstore.dev.theprimetech1.com, api.dev.theprimetech1.com
spec:
  rules:
    - host: renting-api.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: renting-api-service
                port:
                  number: 80
    - host: resource-api.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resource-api-service
                port:
                  number: 80
    - host: inventory-api.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: inventory-api-service
                port:
                  number: 80
    - host: clients-api.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clients-api-service
                port:
                  number: 80
    - host: bookstore.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end-service
                port:
                  number: 80
    - host: api.dev.theprimetech1.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-end-service-proxy
                port:
                  number: 80